### ISSUE TITLE
Fix formatting in README.md

### ISSUE THREAD

**Issue by bdhhtb** [cv9828/SimpleHTTPServer_webpagedesign#2]
I think the first line may be indented, which in Markdown means "this is a code snippet." So the formatting is weird when viewing on GitHub. Unindent that line, and see https://help.github.com/articles/github-flavored-markdown/ for future reference.

**Comment by bdhhtb** [comment]
I'm still seeing the weird formatting:

http://i.imgur.com/z2Z67Us.png

**Comment by cv9828** [comment]
fixed
